version: "3.3"

services:
  alma-inventory:
    image: cedelis/alma-inventory-node:0.3
    ports:
      - 80:80
    volumes:
      - "./local.prop.orgs:/var/data/local.prop.orgs"
      - "./gsheet.prop.json:/usr/src/app/gsheet.prop.json"
    tty: true
    stdin_open: true
